### ISSUE TITLE
打开项目链接报错

### ISSUE THREAD

**Issue by denisdou** [webyang-male/nuxt3-edu#8]
<img width="1351" alt="image" src="https://github.com/webyang-male/nuxt3-edu/assets/16084495/ab1afbb1-9e26-4449-9ae9-949dce26217a">
[Vue warn]: Unhandled error during execution of render function 
  at <Button text="" class="!text-xl !font-bold" onClick=fn<goHome> >
[nuxt] [request error] document is not defined
  at Module.queryElement (./.nuxt/dist/server/server.mjs:9152:5)  
  at Module.mount (./.nuxt/dist/server/server.mjs:9240:49)  
  at Object.wrappedMount [as mount] (./.nuxt/dist/server/server.mjs:8778:49)  
  at renderCallback (./.nuxt/dist/server/server.mjs:30678:66)  
  at onRender (./.nuxt/dist/server/server.mjs:30691:77)  
  at Proxy.render (./.nuxt/dist/server/server.mjs:45869:61)  
  at renderComponentRoot (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:885:16)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:712:28)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
[Vue warn]: Unhandled error during execution of render function 
  at <Button text="" class="!text-xl !font-bold" onClick=fn<goHome> >
[nuxt] [request error] document is not defined
  at Module.queryElement (./.nuxt/dist/server/server.mjs:9152:5)  
  at Module.mount (./.nuxt/dist/server/server.mjs:9240:49)  
  at Object.wrappedMount [as mount] (./.nuxt/dist/server/server.mjs:8778:49)  
  at renderCallback (./.nuxt/dist/server/server.mjs:30678:66)  
  at onRender (./.nuxt/dist/server/server.mjs:30691:77)  
  at Proxy.render (./.nuxt/dist/server/server.mjs:45869:61)  
  at renderComponentRoot (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:885:16)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:712:28)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
[nitro] [dev] [unhandledRejection] ReferenceError: document is not defined
    at Module.queryElement (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:9152:5)
    at Module.mount (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:9240:49)
    at Object.wrappedMount [as mount] (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:8778:49)
    at renderCallback (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:30678:66)
    at onRender (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:30691:77)
    at Proxy.render (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:45869:61)
    at renderComponentRoot (/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:885:16)
    at renderComponentSubTree (/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:712:28)
    at renderComponentVNode (/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12)
    at Module.ssrRenderComponent (/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
    
   点击回到首页
<img width="1298" alt="image" src="https://github.com/webyang-male/nuxt3-edu/assets/16084495/bedfbc71-f6e7-4de9-aa98-ea6e3f100e88">
<img width="1526" alt="image" src="https://github.com/webyang-male/nuxt3-edu/assets/16084495/c109f774-9d79-4123-b67e-3d8dae710458">

**Comment by webyang-male** [comment]
> <img alt="image" width="1351" src="https://private-user-images.githubusercontent.com/16084495/340184544-ab1afbb1-9e26-4449-9ae9-949dce26217a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzMyNDEsIm5iZiI6MTcxOTY3Mjk0MSwicGF0aCI6Ii8xNjA4NDQ5NS8zNDAxODQ1NDQtYWIxYWZiYjEtOWUyNi00NDQ5LTlhZTktOTQ5ZGNlMjYyMTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE0NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMTYyOTdlNzE4ZjgxMWQ2ZWU3YjMwMjYwODIyZDRlYjAwNThjZDUzNzg3YTNhZTJlMWM1MTUyN2QwNjM4NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ssyZfudm5Ah2Bm6iyYpzRANwida79URxM_aV-v_rHpg"> [Vue warn]: Unhandled error during execution of render function at > [nuxt] [request error] document is not defined at Module.queryElement (./.nuxt/dist/server/server.mjs:9152:5) at Module.mount (./.nuxt/dist/server/server.mjs:9240:49) at Object.wrappedMount [as mount] (./.nuxt/dist/server/server.mjs:8778:49) at renderCallback (./.nuxt/dist/server/server.mjs:30678:66) at onRender (./.nuxt/dist/server/server.mjs:30691:77) at Proxy.render (./.nuxt/dist/server/server.mjs:45869:61) at renderComponentRoot (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:885:16) at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:712:28) at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12) at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10) [Vue warn]: Unhandled error during execution of render function at > [nuxt] [request error] document is not defined at Module.queryElement (./.nuxt/dist/server/server.mjs:9152:5) at Module.mount (./.nuxt/dist/server/server.mjs:9240:49) at Object.wrappedMount [as mount] (./.nuxt/dist/server/server.mjs:8778:49) at renderCallback (./.nuxt/dist/server/server.mjs:30678:66) at onRender (./.nuxt/dist/server/server.mjs:30691:77) at Proxy.render (./.nuxt/dist/server/server.mjs:45869:61) at renderComponentRoot (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:885:16) at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:712:28) at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12) at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10) [nitro] [dev] [unhandledRejection] ReferenceError: document is not defined at Module.queryElement (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:9152:5) at Module.mount (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:9240:49) at Object.wrappedMount [as mount] (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:8778:49) at renderCallback (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:30678:66) at onRender (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:30691:77) at Proxy.render (file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:45869:61) at renderComponentRoot (/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:885:16) at renderComponentSubTree (/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:712:28) at renderComponentVNode (/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12) at Module.ssrRenderComponent (/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
> [Vue 警告]：在 >Module.queryElement （./.nuxt/dist/server/server.mjs：9152：5） 在 Module.mount （./.nuxt/dist/server/server.mjs：9240：49） 在 Object.wrappedMount [as mount] （./.nuxt/dist/server/server.mjs：8778：49） 在 renderCallback （./.nuxt/dist/server/server.mjs：30678：66） 在 onRender （./.nuxt/dist/server/server.mjs：30691：77） 在 Proxy.render （./.nuxt/dist/server/server.mjs：45869：61） 在renderComponentSubTree （./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js：885：16） 在 renderComponentSubTree （./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：712：28） 在 renderComponentVNode （./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：641：12） 在 Module.ssrRenderComponent （./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：84：10） [Vue 警告]：在 > 执行渲染函数时出现未处理的错误 [nuxt] [请求错误]] 文档未在 Module.queryElement （./.nuxt/dist/server/server.mjs：9152：5） 中定义 在 Module.mount （./.nuxt/dist/server/server.mjs：9240：49） 中 在 Object.wrappedMount [as mount] （./.nuxt/dist/server/server.mjs：8778：49） 中 renderCallback （./.nuxt/dist/server/server.mjs：30678：66） 中 onRender （./.nuxt/dist/server/server.mjs：30691：77） 中 Proxy.render （./.nuxt/dist/server/server.mjs：45869：61） 中 renderComponentRoot （./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js：885：16） 在 renderComponentSubTree （./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：712：28） 在 renderComponentVNode （./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：641：12） 在 Module.ssrRenderComponent （./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：84：10） [硝基] [开发] [unhandledRejection] ReferenceError：文档未在 Module.queryElement （file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:9152:5） 在 Module.mount （file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:9240:49） 在 Object.wrappedMount [as mount] （file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:8778:49） at renderCallback（file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:30678:66） 在 onRender （file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:30691:77） 在 Proxy.render （file:///Users/doujiajun/work/reviews/dj-speakers-ui/.nuxt/dist/server/server.mjs:45869:61） 在 renderComponentRoot （/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js：885：16） 在 renderComponentSubTree（/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：712：28） 在 renderComponentVNode （/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：641：12） 在 Module.ssrRenderComponent （/Users/doujiajun/work/reviews/dj-speakers-ui/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js：84：10）
> 点击回到首页 <img alt="image" width="1298" src="https://private-user-images.githubusercontent.com/16084495/340184819-bedfbc71-f6e7-4de9-aa98-ea6e3f100e88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzMyNDEsIm5iZiI6MTcxOTY3Mjk0MSwicGF0aCI6Ii8xNjA4NDQ5NS8zNDAxODQ4MTktYmVkZmJjNzEtZjZlNy00ZGU5LWFhOTgtZWE2ZTNmMTAwZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE0NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTIxYmRjZDc4NmY2MWM5ZDljN2RkN2E4OTFhZmNkMzhhYWJmZmQ2YzZkYzE0YTkyZThhNDQwYjBhODE0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5XcF4m-Qi7lJeIScFTYYLTIxALGtABMcXV3O8Z_Kmw"> <img alt="image" width="1526" src="https://private-user-images.githubusercontent.com/16084495/340185015-c109f774-9d79-4123-b67e-3d8dae710458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzMyNDEsIm5iZiI6MTcxOTY3Mjk0MSwicGF0aCI6Ii8xNjA4NDQ5NS8zNDAxODUwMTUtYzEwOWY3NzQtOWQ3OS00MTIzLWI2N2UtM2Q4ZGFlNzEwNDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE0NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NGUxY2M3ZDU1ZmY0Njc1NjgzOTA0OWFjNjBlMzEyODNjMWVlNDA5Yzk2ZTU0N2M0YmE2YTI4YzQ4Y2NmZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nvma6TDyW7jYbSRebfArOMF7dz0bDD7a7EC6EMa_HC0">

拉下dev分支看看
